### ISSUE TITLE
Annotations break methods docstrings 

### ISSUE THREAD

**Issue by piontec** [daizutabi/mkapi#14]
I have a file with the following code:

```python
@pytest.fixture(scope="module")
def chart_path(pytestconfig) -> str:
    """Return a path to the chart under test (from command line argument)."""
    return pytestconfig.getoption("chart_path")
```
`mkapi` in page mode skips this. If I remove the annotation, the docstring is picked up correctly.

**Comment by daizutabi** [comment]
This problem is caused by a `@pytest.fixture` decorator. The decorator changes the source file information of the original function, so that the function is skipped because MkApi decides that it is an external object. This problem was fixed in Version 1.0.3. Please update and check it with your code.

**Comment by piontec** [comment]
Thanks for your explanation! Still, I'm not able to use `mkapi`. With 1.0.3, I get this error (didn't happen with 1.0.2)

```
$ (☸ |N/A) poetry run mkdocs serve
INFO    -  Building documentation... 
/home/piontec/work/giantswarm/git/pytest-helm-charts/pytest_helm_charts/apps/deployment.py:26: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  assert app_name is not ""
/home/piontec/work/giantswarm/git/pytest-helm-charts/pytest_helm_charts/apps/deployment.py:27: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  assert app_version is not ""
/home/piontec/work/giantswarm/git/pytest-helm-charts/pytest_helm_charts/apps/deployment.py:28: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  assert catalog_name is not ""
/home/piontec/work/giantswarm/git/pytest-helm-charts/pytest_helm_charts/apps/deployment.py:29: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  assert catalog_url is not ""
Traceback (most recent call last):
  File "/home/piontec/.cache/pypoetry/virtualenvs/pytest-helm-chart-9WdUBSJG-py3.8/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
  File "/home/piontec/.cache/pypoetry/virtualenvs/pytest-helm-chart-9WdUBSJG-py3.8/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/piontec/.cache/pypoetry/virtualenvs/pytest-helm-chart-9WdUBSJG-py3.8/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/piontec/.cache/pypoetry/virtualenvs/pytest-helm-chart-9WdUBSJG-py3.8/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/piontec/.cache/pypoetry/virtualenvs/pytest-helm-chart-9WdUBSJG-py3.8/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/piontec/.cache/pypoetry/virtualenvs/pytest-helm-chart-9WdUBSJG-py3.8/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/piontec/.cache/pypoetry/virtualenvs/pytest-helm-chart-9WdUBSJG-py3.8/lib/python3.8/site-packages/mkdocs/__main__.py", line 133, in serve_command
    serve.serve(
  File "/home/piontec/.cache/pypoetry/virtualenvs/pytest-helm-chart-9WdUBSJG-py3.8/lib/python3.8/site-packages/mkdocs/commands/serve.py", line 141, in serve
    config = builder()
  File "/home/piontec/.cache/pypoetry/virtualenvs/pytest-helm-chart-9WdUBSJG-py3.8/lib/python3.8/site-packages/mkdocs/commands/serve.py", line 136, in builder
    build(config, live_server=live_server, dirty=dirty)
  File "/home/piontec/.cache/pypoetry/virtualenvs/pytest-helm-chart-9WdUBSJG-py3.8/lib/python3.8/site-packages/mkdocs/commands/build.py", line 236, in build
    config = config['plugins'].run_event('config', config)
  File "/home/piontec/.cache/pypoetry/virtualenvs/pytest-helm-chart-9WdUBSJG-py3.8/lib/python3.8/site-packages/mkdocs/plugins.py", line 94, in run_event
    result = method(item, **kwargs)
  File "/home/piontec/.cache/pypoetry/virtualenvs/pytest-helm-chart-9WdUBSJG-py3.8/lib/python3.8/site-packages/mkapi/plugins/mkdocs.py", line 49, in on_config
    config, self.abs_api_paths = mkapi.plugins.api.create_nav(config)
  File "/home/piontec/.cache/pypoetry/virtualenvs/pytest-helm-chart-9WdUBSJG-py3.8/lib/python3.8/site-packages/mkapi/plugins/api.py", line 23, in create_nav
    page[key], abs_api_paths_ = collect(value, docs_dir, config_dir)
  File "/home/piontec/.cache/pypoetry/virtualenvs/pytest-helm-chart-9WdUBSJG-py3.8/lib/python3.8/site-packages/mkapi/plugins/api.py", line 44, in collect
    module = get_module(package_path)
  File "/home/piontec/.cache/pypoetry/virtualenvs/pytest-helm-chart-9WdUBSJG-py3.8/lib/python3.8/site-packages/mkapi/core/module.py", line 104, in get_module
    module = Module(obj)
  File "<string>", line 4, in __init__
  File "/home/piontec/.cache/pypoetry/virtualenvs/pytest-helm-chart-9WdUBSJG-py3.8/lib/python3.8/site-packages/mkapi/core/module.py", line 27, in __post_init__
    super().__post_init__()
  File "/home/piontec/.cache/pypoetry/virtualenvs/pytest-helm-chart-9WdUBSJG-py3.8/lib/python3.8/site-packages/mkapi/core/structure.py", line 99, in __post_init__
    self.members = self.get_members()
  File "/home/piontec/.cache/pypoetry/virtualenvs/pytest-helm-chart-9WdUBSJG-py3.8/lib/python3.8/site-packages/mkapi/core/module.py", line 48, in get_members
    return get_members(self.obj)
  File "/home/piontec/.cache/pypoetry/virtualenvs/pytest-helm-chart-9WdUBSJG-py3.8/lib/python3.8/site-packages/mkapi/core/module.py", line 81, in get_members
    module = get_module(name)
  File "/home/piontec/.cache/pypoetry/virtualenvs/pytest-helm-chart-9WdUBSJG-py3.8/lib/python3.8/site-packages/mkapi/core/module.py", line 104, in get_module
    module = Module(obj)
  File "<string>", line 4, in __init__
  File "/home/piontec/.cache/pypoetry/virtualenvs/pytest-helm-chart-9WdUBSJG-py3.8/lib/python3.8/site-packages/mkapi/core/module.py", line 28, in __post_init__
    self.node = get_node(self.obj)
  File "/home/piontec/.cache/pypoetry/virtualenvs/pytest-helm-chart-9WdUBSJG-py3.8/lib/python3.8/site-packages/mkapi/core/node.py", line 211, in get_node
    return Node(obj, sourcefile_index)
  File "<string>", line 5, in __init__
  File "/home/piontec/.cache/pypoetry/virtualenvs/pytest-helm-chart-9WdUBSJG-py3.8/lib/python3.8/site-packages/mkapi/core/node.py", line 29, in __post_init__
    super().__post_init__()
  File "/home/piontec/.cache/pypoetry/virtualenvs/pytest-helm-chart-9WdUBSJG-py3.8/lib/python3.8/site-packages/mkapi/core/structure.py", line 99, in __post_init__
    self.members = self.get_members()
  File "/home/piontec/.cache/pypoetry/virtualenvs/pytest-helm-chart-9WdUBSJG-py3.8/lib/python3.8/site-packages/mkapi/core/node.py", line 58, in get_members
    return get_members(self.obj)
  File "/home/piontec/.cache/pypoetry/virtualenvs/pytest-helm-chart-9WdUBSJG-py3.8/lib/python3.8/site-packages/mkapi/core/node.py", line 191, in get_members
    member = get_node(obj, sourcefile_index)
  File "/home/piontec/.cache/pypoetry/virtualenvs/pytest-helm-chart-9WdUBSJG-py3.8/lib/python3.8/site-packages/mkapi/core/node.py", line 211, in get_node
    return Node(obj, sourcefile_index)
  File "<string>", line 5, in __init__
  File "/home/piontec/.cache/pypoetry/virtualenvs/pytest-helm-chart-9WdUBSJG-py3.8/lib/python3.8/site-packages/mkapi/core/node.py", line 29, in __post_init__
    super().__post_init__()
  File "/home/piontec/.cache/pypoetry/virtualenvs/pytest-helm-chart-9WdUBSJG-py3.8/lib/python3.8/site-packages/mkapi/core/structure.py", line 94, in __post_init__
    signature = get_signature(obj)
  File "/home/piontec/.cache/pypoetry/virtualenvs/pytest-helm-chart-9WdUBSJG-py3.8/lib/python3.8/site-packages/mkapi/core/signature.py", line 330, in get_signature
    return Signature(obj)
  File "<string>", line 7, in __init__
  File "/home/piontec/.cache/pypoetry/virtualenvs/pytest-helm-chart-9WdUBSJG-py3.8/lib/python3.8/site-packages/mkapi/core/signature.py", line 77, in __post_init__
    self.returns = to_string(return_annotation, "returns", obj=self.obj)
  File "/home/piontec/.cache/pypoetry/virtualenvs/pytest-helm-chart-9WdUBSJG-py3.8/lib/python3.8/site-packages/mkapi/core/signature.py", line 196, in to_string
    return a_of_b(annotation, obj=obj)
  File "/home/piontec/.cache/pypoetry/virtualenvs/pytest-helm-chart-9WdUBSJG-py3.8/lib/python3.8/site-packages/mkapi/core/signature.py", line 224, in a_of_b
    type_ = f"{name} of " + to_string(annotation.__args__[0], obj=obj)
  File "/home/piontec/.cache/pypoetry/virtualenvs/pytest-helm-chart-9WdUBSJG-py3.8/lib/python3.8/site-packages/mkapi/core/signature.py", line 198, in to_string
    return to_string_args(annotation, obj=obj)
  File "/home/piontec/.cache/pypoetry/virtualenvs/pytest-helm-chart-9WdUBSJG-py3.8/lib/python3.8/site-packages/mkapi/core/signature.py", line 299, in to_string_args
    args = ", ".join(to_string(x, obj=obj) for x in args)
  File "/home/piontec/.cache/pypoetry/virtualenvs/pytest-helm-chart-9WdUBSJG-py3.8/lib/python3.8/site-packages/mkapi/core/signature.py", line 299, in <genexpr>
    args = ", ".join(to_string(x, obj=obj) for x in args)
  File "/home/piontec/.cache/pypoetry/virtualenvs/pytest-helm-chart-9WdUBSJG-py3.8/lib/python3.8/site-packages/mkapi/core/signature.py", line 186, in to_string
    args = [to_string(x, obj=obj) for x in annotation.__args__]
  File "/home/piontec/.cache/pypoetry/virtualenvs/pytest-helm-chart-9WdUBSJG-py3.8/lib/python3.8/site-packages/mkapi/core/signature.py", line 186, in <listcomp>
    args = [to_string(x, obj=obj) for x in annotation.__args__]
  File "/home/piontec/.cache/pypoetry/virtualenvs/pytest-helm-chart-9WdUBSJG-py3.8/lib/python3.8/site-packages/mkapi/core/signature.py", line 176, in to_string
    return union(annotation, obj=obj)
  File "/home/piontec/.cache/pypoetry/virtualenvs/pytest-helm-chart-9WdUBSJG-py3.8/lib/python3.8/site-packages/mkapi/core/signature.py", line 255, in union
    args = [to_string(x, obj=obj) for x in args]
  File "/home/piontec/.cache/pypoetry/virtualenvs/pytest-helm-chart-9WdUBSJG-py3.8/lib/python3.8/site-packages/mkapi/core/signature.py", line 255, in <listcomp>
    args = [to_string(x, obj=obj) for x in args]
  File "/home/piontec/.cache/pypoetry/virtualenvs/pytest-helm-chart-9WdUBSJG-py3.8/lib/python3.8/site-packages/mkapi/core/signature.py", line 166, in to_string
    return resolve_forward_arg(obj, annotation.__forward_arg__)
  File "/home/piontec/.cache/pypoetry/virtualenvs/pytest-helm-chart-9WdUBSJG-py3.8/lib/python3.8/site-packages/mkapi/core/signature.py", line 324, in resolve_forward_arg
    type = eval(name, globals)
  File "<string>", line 1, in <module>
NameError: name 'YamlDict' is not defined
```

My type definition for `YamlDict` is:

```python
YamlDict = Dict[str, Union[int, float, str, bool, 'YamlDict']]
```

**Comment by daizutabi** [comment]
I would like to solve this issue, but the definition is cyclic:

<img width="479" alt="img" src="https://user-images.githubusercontent.com/17495937/84880667-c814ac80-b0c7-11ea-8734-d8b68b46b275.png">

**Comment by piontec** [comment]
Yes, that's the point. It's still a valid definition, right?

**Comment by daizutabi** [comment]
In version 1.0.5, I fixed this problem by just catching `NameError` and returning a string (in this case, `'YamlDict'`) instead of `type`.

I think `YamlDict` on the left hand side is just alias or shorthand notation. That has no relationship with `'YamlDict'` on the right hand side.

**Comment by piontec** [comment]
Forward references are part of the type hinting spec, they should be correctly evaluated, check here: https://www.python.org/dev/peps/pep-0484/#forward-references
But still, returning just a string is something to get started :)

**Comment by daizutabi** [comment]
It says: "When a type hint contains names that have not been defined yet, that definition may be expressed as a string literal, to be resolved later."

That's exactly what MkApi does. 

```python
YamlDict = Dict[str, Union[int, float, str, bool, 'YamlDict']]
```
is not a definition but an assignment, and `YamlDict` is not an instance of `type`:

<img width="512" alt="img" src="https://user-images.githubusercontent.com/17495937/85078177-cbf71a80-b1fe-11ea-9ca9-6dca2da76715.png">

**Comment by piontec** [comment]
You're right, so that's in sync with the spec now. I'm happy this will work now :) I think this can be closed now.
