### ISSUE TITLE
Multiple assignments per line: list index out of range

### ISSUE THREAD

**Issue by Ahrak** [daizutabi/mkapi#15]
I get a n error with the latest commit (6fe41e2).
Does not occur in the previous commit.

It think the problem is if the code has multiple assignments per line:

```python
class Test():
    """ bla bla blubb
    
    Attributes: 
        _foo: a foobar value
    """

    def __init__(self):
        """ initizizes test object """
        self._foo: str = "BAR"
        self._bar: int = 0

    def class_method(self, bar: str = "BAR") -> float:
        """ class method

        Args:
            bar: blubb
        """
        self._foo = bar
        self._foo, self._bar = bar, 0 # booom crash!
        return 0.0
```

**Trace**:
```
Traceback (most recent call last):
  File "./mkapi/.env/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
  File "./mkapi/.env/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "./mkapi/.env/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "./mkapi/.env/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "./mkapi/.env/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "./mkapi/.env/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "./mkapi/.env/lib/python3.8/site-packages/mkdocs/__main__.py", line 152, in build_command
    build.build(config.load_config(**kwargs), dirty=not clean)
  File "./mkapi/.env/lib/python3.8/site-packages/mkdocs/commands/build.py", line 271, in build
    _populate_page(file.page, config, files, dirty)
  File "./mkapi/.env/lib/python3.8/site-packages/mkdocs/commands/build.py", line 167, in _populate_page
    page.markdown = config['plugins'].run_event(
  File "./mkapi/.env/lib/python3.8/site-packages/mkdocs/plugins.py", line 94, in run_event
    result = method(item, **kwargs)
  File "./mkapi/mkapi/plugins/mkdocs.py", line 108, in on_page_markdown
    page = Page(markdown, abs_src_path, self.abs_api_paths)
  File "<string>", line 6, in __init__
  File "./mkapi/mkapi/core/page.py", line 37, in __post_init__
    self.markdown = "\n\n".join(self.split(source))
  File "./mkapi/mkapi/core/page.py", line 64, in split
    node = get_node(name)
  File "./mkapi/mkapi/core/node.py", line 209, in get_node
    return Node(obj, sourcefile_index)
  File "<string>", line 5, in __init__
  File "./mkapi/mkapi/core/node.py", line 30, in __post_init__
    super().__post_init__()
  File "./mkapi/mkapi/core/structure.py", line 104, in __post_init__
    self.members = self.get_members()
  File "./mkapi/mkapi/core/node.py", line 59, in get_members
    return get_members(self.obj)
  File "./mkapi/mkapi/core/node.py", line 189, in get_members
    member = get_node(obj, sourcefile_index)
  File "./mkapi/mkapi/core/node.py", line 209, in get_node
    return Node(obj, sourcefile_index)
  File "<string>", line 5, in __init__
  File "./mkapi/mkapi/core/node.py", line 30, in __post_init__
    super().__post_init__()
  File "./mkapi/mkapi/core/structure.py", line 99, in __post_init__
    signature = get_signature(obj)
  File "./mkapi/mkapi/core/signature.py", line 330, in get_signature
    return Signature(obj)
  File "<string>", line 7, in __init__
  File "./mkapi/mkapi/core/signature.py", line 71, in __post_init__
    self.set_attributes()
  File "./mkapi/mkapi/core/signature.py", line 109, in set_attributes
    for name, (type, description) in get_attributes(self.obj).items():
  File "./mkapi/mkapi/core/attribute.py", line 219, in get_attributes
    return get_class_attributes(obj)
  File "./mkapi/mkapi/core/attribute.py", line 165, in get_class_attributes
    return get_attributes_dict(attr_lineno, source, prefix="self.")
  File "./mkapi/mkapi/core/attribute.py", line 146, in get_attributes_dict
    description = get_description(lines[:stop], lineno)
  File "./mkapi/mkapi/core/attribute.py", line 67, in get_description
    line = lines[index]
IndexError: list index out of range
```

**Comment by daizutabi** [comment]
Thanks for reporting this issue.
This issue has been fixed in Version 1.0.5 by skipping multiple assignments per line, because there is no valid way to add description by comment for multiple attributes at the same time.
