### ISSUE TITLE
ValueError: Could not find object: <module> in GH actions/readthedocs

### ISSUE THREAD

**Issue by pwwang** [daizutabi/mkapi#31]
I can successfully run it locally. However, when I try to deploy it via GH actions or rtd, both gave the same error:

<details>
<summary>Traceback</summary>
<pre>
Traceback (most recent call last):
  File "/home/docs/.pyenv/versions/3.7.3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/docs/.pyenv/versions/3.7.3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/docs/checkouts/readthedocs.org/user_builds/python-varname/envs/cleanup/lib/python3.7/site-packages/mkdocs/__main__.py", line 192, in <module>
    cli()
  File "/home/docs/checkouts/readthedocs.org/user_builds/python-varname/envs/cleanup/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/python-varname/envs/cleanup/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/docs/checkouts/readthedocs.org/user_builds/python-varname/envs/cleanup/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/docs/checkouts/readthedocs.org/user_builds/python-varname/envs/cleanup/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/docs/checkouts/readthedocs.org/user_builds/python-varname/envs/cleanup/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/python-varname/envs/cleanup/lib/python3.7/site-packages/mkdocs/__main__.py", line 152, in build_command
    build.build(config.load_config(**kwargs), dirty=not clean)
  File "/home/docs/checkouts/readthedocs.org/user_builds/python-varname/envs/cleanup/lib/python3.7/site-packages/mkdocs/commands/build.py", line 236, in build
    config = config['plugins'].run_event('config', config)
  File "/home/docs/checkouts/readthedocs.org/user_builds/python-varname/envs/cleanup/lib/python3.7/site-packages/mkdocs/plugins.py", line 94, in run_event
    result = method(item, **kwargs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/python-varname/envs/cleanup/lib/python3.7/site-packages/mkapi/plugins/mkdocs.py", line 51, in on_config
    config, self.config["filters"]
  File "/home/docs/checkouts/readthedocs.org/user_builds/python-varname/envs/cleanup/lib/python3.7/site-packages/mkapi/plugins/api.py", line 24, in create_nav
    value, docs_dir, config_dir, global_filters
  File "/home/docs/checkouts/readthedocs.org/user_builds/python-varname/envs/cleanup/lib/python3.7/site-packages/mkapi/plugins/api.py", line 47, in collect
    module = get_module(package_path)
  File "/home/docs/checkouts/readthedocs.org/user_builds/python-varname/envs/cleanup/lib/python3.7/site-packages/mkapi/core/module.py", line 96, in get_module
    obj = get_object(name)
  File "/home/docs/checkouts/readthedocs.org/user_builds/python-varname/envs/cleanup/lib/python3.7/site-packages/mkapi/core/object.py", line 39, in get_object
    raise ValueError(f"Could not find object: {name}")
ValueError: Could not find object: varname
</pre>
</details>

And you can see the configurations here:

https://github.com/pwwang/python-varname/tree/857b4c0206e4315d00a3ab85ceb932e9aebf1f69

**Comment by pwwang** [comment]
Closing this.

This is due to the env being switched.
